version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    networks:
      - minhaapp-network
    volumes:
      - minhaapp-db-volume:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minhaappweb:latest
    depends_on:
      - db
    networks:
      - minhaapp-network
    environment:
      - DOTNET_SDK_VERSION=8.0
    ports:
      - "8080:8080"

networks:
  minhaapp-network:
    driver: bridge

volumes:
  minhaapp-db-volume:
